-- public.companies definition

-- Drop table

-- DROP TABLE companies;

CREATE TABLE companies (
                           id int4 NOT NULL GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
                           title varchar(255) NOT NULL,
                           leader_name varchar(255) NOT NULL,
                           contract_person varchar(255) NOT NULL,
                           responsible_person varchar(255) NOT NULL,
                           phone_number varchar(255) NOT NULL,
                           mail varchar(255) NOT NULL,
                           "comment" text NOT NULL,
                           head_company varchar NOT NULL,
                           address varchar NOT NULL,
                           head_other varchar(255) NOT NULL,
                           contract_number_ip varchar NOT NULL,
                           agent_information varchar NOT NULL,
                           avatar varchar NOT NULL,
                           print_statement bool NOT NULL DEFAULT false,
                           header_doc bool NOT NULL DEFAULT false,
                           flat_plates bool NOT NULL DEFAULT false,
                           flat_plates2 bool NOT NULL DEFAULT false,
                           flat_plates3 bool NOT NULL DEFAULT false,
                           flat_plates4 bool NOT NULL DEFAULT false,
                           report_module bool NOT NULL DEFAULT false,
                           type_organization bool NOT NULL DEFAULT false,
                           contract_number varchar(255) NOT NULL,
                           CONSTRAINT companies_pk PRIMARY KEY (id)
);


-- public.owner_types definition

-- Drop table

-- DROP TABLE owner_types;

CREATE TABLE owner_types (
                             id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( NO MINVALUE NO MAXVALUE NO CYCLE),
                             title varchar NOT NULL,
                             CONSTRAINT owner_types_pk PRIMARY KEY (id)
);

INSERT INTO owner_types (id, title) VALUES(1, 'Физическое лицо');
INSERT INTO owner_types (id, title) VALUES(2, 'Юридическое лицо');
INSERT INTO owner_types (id, title) VALUES(3, 'Неопределено');

-- public.plate_types definition

-- Drop table

-- DROP TABLE plate_types;

CREATE TABLE plate_types (
                             id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( NO MINVALUE NO MAXVALUE NO CYCLE),
                             title varchar(100) NOT NULL,
                             mask varchar(100) NOT NULL,
                             placeholder varchar(100) NOT NULL,
                             regexp varchar(100) NOT NULL,
                             CONSTRAINT plate_types_pk PRIMARY KEY (id)
);

INSERT INTO plate_types (id, title, mask, placeholder, regexp) VALUES(1, 'Тип-1хх', 'Я ### ЯЯ ##', 'А 000 АА 00', '[авекмнорстухАВЕКМНОРСТУХ]{1}\\s*[0-9]{3}\\s*[авекмнорстухАВЕКМНОРСТУХ]{2}\\s*[0-9]{2}');
INSERT INTO plate_types (id, title, mask, placeholder, regexp) VALUES(2, 'Тип-1ххх', 'Я ### ЯЯ ###', 'А 000 АА 000', '[авекмнорстухАВЕКМНОРСТУХ]{1}\\s*[0-9]{3}\\s*[авекмнорстухАВЕКМНОРСТУХ]{2}\\s*[0-9]{3}');
INSERT INTO plate_types (id, title, mask, placeholder, regexp) VALUES(3, 'Тип-1Аxx', 'Я ### ЯЯ ##', 'А 000 АА 00', '[авекмнорстухАВЕКМНОРСТУХ]{1}\\s*[0-9]{3}\\s*[авекмнорстухАВЕКМНОРСТУХ]{2}\\s*[0-9]{2}');
INSERT INTO plate_types (id, title, mask, placeholder, regexp) VALUES(4, 'Тип-1Аxxx', 'Я ### ЯЯ ###', 'А 000 АА 000', '[авекмнорстухАВЕКМНОРСТУХ]{1}\\s*[0-9]{3}\\s*[авекмнорстухАВЕКМНОРСТУХ]{2}\\s*[0-9]{3}');
INSERT INTO plate_types (id, title, mask, placeholder, regexp) VALUES(5, 'Тип-1БФхх', 'Я ### ЯЯ ##', 'А 000 АА 00', '[авекмнорстухАВЕКМНОРСТУХ]{1}\\s*[0-9]{3}\\s*[авекмнорстухАВЕКМНОРСТУХ]{2}\\s*[0-9]{2}');
INSERT INTO plate_types (id, title, mask, placeholder, regexp) VALUES(6, 'Тип-1БФххх', 'Я ### ЯЯ ###', 'А 000 АА 000', '[авекмнорстухАВЕКМНОРСТУХ]{1}\\s*[0-9]{3}\\s*[авекмнорстухАВЕКМНОРСТУХ]{2}\\s*[0-9]{3}');
INSERT INTO plate_types (id, title, mask, placeholder, regexp) VALUES(7, 'Тип-1бхх', 'ЯЯ ### ##', 'АА 000 00', '[авекмнорстухАВЕКМНОРСТУХ]{2}\\s*[0-9]{3}\\s*[0-9]{2}');
INSERT INTO plate_types (id, title, mask, placeholder, regexp) VALUES(8, 'Тип-2', 'ЯЯ #### ##', 'АА 0000 00', '[авекмнорстухАВЕКМНОРСТУХ]{2}\\s*[0-9]{4}\\s*[0-9]{2}');
INSERT INTO plate_types (id, title, mask, placeholder, regexp) VALUES(9, 'Тип-3', '#### ЯЯ ##', '0000 АА 00', '[0-9]{4}\\s*[авекмнорстухАВЕКМНОРСТУХ]{2}\\s[0-9]{2}');
INSERT INTO plate_types (id, title, mask, placeholder, regexp) VALUES(10, 'Тип-4.1', '#### ЯЯ ##', '0000 АА 00', '[0-9]{4}\\s*[авекмнорстухАВЕКМНОРСТУХ]{2}\\s[0-9]{2}');
INSERT INTO plate_types (id, title, mask, placeholder, regexp) VALUES(11, 'Тип-4.2', '#### ЯЯ ##', '0000 АА 00', '[0-9]{4}\\s*[авекмнорстухАВЕКМНОРСТУХ]{2}\\s[0-9]{2}');
INSERT INTO plate_types (id, title, mask, placeholder, regexp) VALUES(12, 'Тип-1А БФxx', 'Я ### ЯЯ ##', 'А 000 АА 00', '[авекмнорстухАВЕКМНОРСТУХ]{1}\\s*[0-9]{3}\\s*[авекмнорстухАВЕКМНОРСТУХ]{2}\\s*[0-9]{2}');
INSERT INTO plate_types (id, title, mask, placeholder, regexp) VALUES(13, 'Тип-1А БФxxx', 'Я ### ЯЯ ###', 'А 000 АА 000', '[авекмнорстухАВЕКМНОРСТУХ]{1}\\s*[0-9]{3}\\s*[авекмнорстухАВЕКМНОРСТУХ]{2}\\s*[0-9]{3}');




-- public.roles definition

-- Drop table

-- DROP TABLE roles;

CREATE TABLE roles (
                       id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( NO MINVALUE NO MAXVALUE NO CYCLE),
                       "role" varchar NOT NULL,
                       CONSTRAINT role_pk PRIMARY KEY (id)
);

INSERT INTO roles (id, "role") VALUES(1, 'Админ');
INSERT INTO roles (id, "role") VALUES(2, 'Младший Админ');
INSERT INTO roles (id, "role") VALUES(3, 'Модератор');
INSERT INTO roles (id, "role") VALUES(4, 'Агент');


-- public.status_products definition

-- Drop table

-- DROP TABLE status_products;

CREATE TABLE status_products (
                                 id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( NO MINVALUE NO MAXVALUE NO CYCLE),
                                 title varchar NOT NULL,
                                 CONSTRAINT status_products_pk PRIMARY KEY (id)
);

INSERT INTO status_products (id, title) VALUES(1, 'Ожидается проверка');
INSERT INTO status_products (id, title) VALUES(2, 'Добавлено');
INSERT INTO status_products (id, title) VALUES(3, 'Отправлено на редактирование');
INSERT INTO status_products (id, title) VALUES(4, 'Отправлено на перепроверку');


-- public.type_document_owners definition

-- Drop table

-- DROP TABLE type_document_owners;

CREATE TABLE type_document_owners (
                                      id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( NO MINVALUE NO MAXVALUE NO CYCLE),
                                      title varchar NOT NULL,
                                      CONSTRAINT type_document_owners_pk PRIMARY KEY (id)
);

INSERT INTO type_document_owners (id, title) VALUES(1, 'Паспорт гражданина РФ');
INSERT INTO type_document_owners (id, title) VALUES(2, 'Иные формы документов');
INSERT INTO type_document_owners (id, title) VALUES(3, 'Неопределено');
-- public.type_document_transport definition

-- Drop table

-- DROP TABLE type_document_transport;

CREATE TABLE type_document_transport (
                                         id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( NO MINVALUE NO MAXVALUE NO CYCLE),
                                         title varchar(100) NOT NULL,
                                         mask varchar(100) NOT NULL,
                                         placeholder varchar(100) NOT NULL,
                                         regexp varchar(100) NOT NULL,
                                         CONSTRAINT newtable_pk PRIMARY KEY (id)
);

INSERT INTO type_document_transport (id, title, mask, placeholder, regexp) VALUES(1, 'СРТС', 'DD DD ######', '00 00 000000', '[0-9a-zA-Zа-яА-я]{2}\s[0-9a-zA-Zа-яА-я]{2}\s[0-9]{6}');
INSERT INTO type_document_transport (id, title, mask, placeholder, regexp) VALUES(2, 'ПТС', 'DD DD ######', '00 00 000000', '[0-9a-zA-Zа-яА-я]{2}\s[0-9a-zA-Zа-яА-я]{2}\s[0-9]{6}');
INSERT INTO type_document_transport (id, title, mask, placeholder, regexp) VALUES(3, 'ЭЛЕКТРОННОЕ ПТС', '###############', '000000000000000', '[0-9]{15}');

-- public.defect_products definition

-- Drop table

-- DROP TABLE defect_products;

CREATE TABLE defect_products (
                                 id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( NO MINVALUE NO MAXVALUE NO CYCLE),
                                 license_plate varchar NOT NULL,
                                 count_plate smallserial NOT NULL,
                                 date_create date NOT NULL,
                                 company_id int4 NOT NULL,
                                 plate_type_id int4 NOT NULL,
                                 created_at timestamp NOT NULL DEFAULT now(),
                                 CONSTRAINT defect_products_pk PRIMARY KEY (id),
                                 CONSTRAINT defect_products_fk FOREIGN KEY (company_id) REFERENCES companies(id),
                                 CONSTRAINT defect_products_fk_1 FOREIGN KEY (plate_type_id) REFERENCES plate_types(id)
);


-- public.products definition

-- Drop table

-- DROP TABLE products;

CREATE TABLE products (
                          id serial4 NOT NULL,
                          license_plate varchar(255) NOT NULL,
                          issued_doc varchar(255) NOT NULL,
                          representative_document_issued_doc varchar(255) NOT NULL,
                          individual_document_issued_doc varchar(255) NOT NULL,
                          serial_number varchar(255) NOT NULL,
                          date_create date NOT NULL,
                          date_issuing date NOT NULL,
                          "document" varchar(255) NOT NULL,
                          date_issuing_transport_document varchar(255) NOT NULL,
                          count_plate int4 NOT NULL,
                          individual_document_other_type varchar(255) NOT NULL,
                          individual_document_surname varchar(255) NOT NULL,
                          individual_document_name varchar(255) NOT NULL,
                          individual_document_patronymic varchar(255) NOT NULL,
                          individual_document_serial_number varchar(255) NOT NULL,
                          individual_document_date_issuing varchar(255) NOT NULL,
                          entity_document_name varchar(255) NOT NULL,
                          entity_document_inn varchar(255) NOT NULL,
                          entity_document_orgn varchar(255) NOT NULL,
                          representative_individual_document_other_type varchar(255) NOT NULL,
                          representative_individual_document_surname varchar(255) NOT NULL,
                          representative_individual_document_name varchar(255) NOT NULL,
                          representative_individual_document_patronymic varchar(255) NOT NULL,
                          representative_individual_document_serial_number varchar(255) NOT NULL,
                          representative_individual_document_date_issuing varchar(255) NOT NULL,
                          representative_entity_document_name varchar(255) NOT NULL,
                          representative_entity_document_inn varchar(255) NOT NULL,
                          representative_entity_document_orgn varchar(255) NOT NULL,
                          company_id int4 NOT NULL,
                          plate_type_id int4 NOT NULL,
                          type_document_owner_id int4 NOT NULL,
                          type_document_transport_id int4 NOT NULL,
                          owner_type_id int4 NOT NULL,
                          status_product_id int4 NOT NULL DEFAULT 1,
                          representative_type_owner_id int4 NOT NULL,
                          representative_document_type_owner_id int4 NOT NULL,
                          created_at timestamp NOT NULL DEFAULT now(),
                          CONSTRAINT products_pk PRIMARY KEY (id),
                          CONSTRAINT products_fk FOREIGN KEY (company_id) REFERENCES companies(id),
                          CONSTRAINT products_fk_1 FOREIGN KEY (type_document_owner_id) REFERENCES type_document_owners(id),
                          CONSTRAINT products_fk_2 FOREIGN KEY (representative_document_type_owner_id) REFERENCES type_document_owners(id),
                          CONSTRAINT products_fk_3 FOREIGN KEY (owner_type_id) REFERENCES owner_types(id),
                          CONSTRAINT products_fk_4 FOREIGN KEY (representative_type_owner_id) REFERENCES owner_types(id),
                          CONSTRAINT products_fk_5 FOREIGN KEY (plate_type_id) REFERENCES plate_types(id),
                          CONSTRAINT products_fk_6 FOREIGN KEY (status_product_id) REFERENCES status_products(id),
                          CONSTRAINT products_fk_7 FOREIGN KEY (type_document_transport_id) REFERENCES type_document_transport(id)
);


-- public.store definition

-- Drop table

-- DROP TABLE store;

CREATE TABLE store (
                       company_id int4 NOT NULL,
                       plate_type_id int4 NOT NULL,
                       count int4 NOT NULL DEFAULT 0,
                       used bool NOT NULL DEFAULT false,
                       CONSTRAINT store_fk FOREIGN KEY (company_id) REFERENCES companies(id),
                       CONSTRAINT store_fk_1 FOREIGN KEY (plate_type_id) REFERENCES plate_types(id)
);


-- public.users definition

-- Drop table

-- DROP TABLE users;

CREATE TABLE users (
                       id uuid NOT NULL,
                       login varchar(255) NOT NULL,
                       email varchar NOT NULL,
                       "password" varchar NOT NULL,
                       "blocked" bool NOT NULL DEFAULT false,
                       "comment" text NOT NULL,
                       phone_number varchar NOT NULL,
                       surname varchar NOT NULL,
                       "name" varchar NOT NULL,
                       patronymic varchar NOT NULL,
                       address varchar NOT NULL,
                       last_login timestamptz NULL,
                       role_id int4 NOT NULL,
                       CONSTRAINT user_pk PRIMARY KEY (id),
                       CONSTRAINT user_fk FOREIGN KEY (role_id) REFERENCES roles(id)
);


-- public.work_place definition

-- Drop table

-- DROP TABLE work_place;

CREATE TABLE work_place (
                            user_id uuid NOT NULL,
                            company_id int4 NOT NULL,
                            CONSTRAINT place_work_fk FOREIGN KEY (company_id) REFERENCES companies(id),
                            CONSTRAINT place_work_fk_1 FOREIGN KEY (user_id) REFERENCES users(id)
);


-- public.documents_statement definition

-- Drop table

-- DROP TABLE documents_statement;

CREATE TABLE documents_statement (
                                     url varchar(255) NOT NULL,
                                     "name" varchar(255) NOT NULL,
                                     "delete" bool NOT NULL DEFAULT false,
                                     product_id serial4 NOT NULL,
                                     CONSTRAINT documents_statement_fk FOREIGN KEY (product_id) REFERENCES products(id)
);


-- public.documents_statement_tc definition

-- Drop table

-- DROP TABLE documents_statement_tc;

CREATE TABLE documents_statement_tc (
                                        url varchar(255) NOT NULL,
                                        "name" varchar(255) NOT NULL,
                                        "delete" bool NOT NULL DEFAULT false,
                                        product_id serial4 NOT NULL,
                                        CONSTRAINT documents_statement_tc_fk FOREIGN KEY (product_id) REFERENCES products(id)
);


-- public.info_edit_messages definition

-- Drop table

-- DROP TABLE info_edit_messages;

CREATE TABLE info_edit_messages (
                                    message varchar NOT NULL,
                                    edited bool NOT NULL DEFAULT false,
                                    product_id serial4 NOT NULL,
                                    id serial4 NOT NULL,
                                    CONSTRAINT info_edit_messages_pk PRIMARY KEY (id),
                                    CONSTRAINT info_edit_messages_fk FOREIGN KEY (product_id) REFERENCES products(id)
);